version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 8080:80
    volumes:
      # Монтируем папку из нашей ос
      - .:/var/www/html
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=laravelpass
    ports:
      - '3307:3306'
    volumes:
      - ./storage/docker/mysql:/bitnami