version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 8080:80
    volumes:
      # Монтируем папку из нашей ос
      - .:/var/www/html
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=laravelpass
    ports:
      - '54320:5432'
    volumes:
      - ./storage/docker/postgres:/var/lib/postgresql/data